ubuntu_base:
  path: ubuntu/xenial/base
  tag: "jderobot/ubuntu:base"
  build: False
  push: False           
  
official:
  path: jderobot/official
  tag: "jderobot/jderobot"
  build: True
  push: True

###### DEVELOPMENT #######
dev-only-ice:
  path: jderobot/dev-only-ice
  tag: "jderobot/jderobot:dev-only-ice"
  build: False
  push: False

dev:
  path: jderobot/dev
  tag: "jderobot/jderobot:dev"
  build: False
  push: False

jenkins:
  path: jenkins/dev
  tag: "jderobot/jenkins:dev"
  build: False 
  push: False

####### DEMOS #######
cameraviewjs:
  path: jderobot/demos/cameraviewjs
  tag: "jderobot/demos:cameraviewjs"
  build: False
  push: False
